version: 2.26.1
name: fefu-queries-test

services:
  backend:
    restart: always
    build: ./backend
    environment:
      JWT_SECRET: qwerty
      MONGO_HOST: fefu-queries-mongo
      MONGO_USER: root
      MONGO_PASSWORD: password
      MONGO_DATABASE: fefu-queries
    ports:
      - 8000:8000

  mongo:
    image: mongo
    container_name: fefu-queries-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: fefu-queries
